### ISSUE TITLE
Consumer API - Basic usage example

### ISSUE THREAD

**Issue by ivanchaer** [nuvoleweb/integration#10]
Hi Antonio,

I'm a bit lost with using the consumer via the API. 
I saw the "coming soon..." on the docs.
Would you have an example of how to create a consumer programmatically, equivalent to the [example from producer](https://github.com/nuvoleweb/integration/wiki/4.-Producer)?
Or is it best to import via standalone migrations for now?

Many thanks,
Ivan

**Comment by ademarco** [comment]
I've actually pushed some code related to this issue, I'll update the documentation too.

**Comment by ademarco** [comment]
There you go! https://github.com/nuvoleweb/integration/wiki/5.-Consumer
