### ISSUE TITLE
Exception when the field is not defined 

### ISSUE THREAD

**Issue by antonov** [nuvoleweb/integration#6]
Hello! 

I am using your module to migrate the content with json.

When a field is not exist in one of the languages defined in languages array, i have an exception produced in this line: 

https://github.com/nuvoleweb/integration/blob/7.x-1.x/src/Document/Document.php#L135

Undefined property: stdClass::$und File /var/www/html/platform/sites/all/modules/contrib/integration/src/Document/Document.php, line 134(file: /var/www/html/platform/sites/all/modules/contrib/integration/src/Document/Document.php, line 134)

Error   array_shift() expects parameter 1 to be array, null given File /var/www/html/platform/sites/all/modules/contrib/integration/src/Document/Document.php, line 135

If i change the "<" symbol to ">" it works fine but with a notice in line 134.

Thanks!

**Comment by ademarco** [comment]
Thank you for reporting! Please try if code on `6-field-is-not-defined` branch fixes the issue as I was not able to entirely reproduce it.

**Comment by antonov** [comment]
Hello @ademarco,
Thank you very much for a fix, i tried to import with the code from specified branch and now is working as expected.
Best regards,
Artem.

**Comment by ademarco** [comment]
Perfect, merging and closing.
